# Generated by Django 4.2.7 on 2023-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_A', models.CharField(max_length=20)),
                ('ticker_B', models.CharField(max_length=20)),
                ('corr', models.FloatField()),
                ('calc_dt', models.DateTimeField()),
                ('status', models.CharField(choices=[('ST', 'STRONG'), ('MD', 'MEDIUM'), ('WK', 'WEAK'), ('NN', 'NONE')], default='NN', max_length=2)),
            ],
            options={
                'db_table': 'algo_pack.correlations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrelationsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'correlations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AlgoPack',
        ),
    ]
