# Generated by Django 4.2.7 on 2023-12-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_correlations_correlationsdb_delete_algopack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correlations',
            options={'managed': False, 'ordering': ('correlation',)},
        ),
        migrations.AlterModelTable(
            name='correlations',
            table='correlations',
        ),
    ]
