# Generated by Django 4.2.7 on 2023-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_correlations_options_alter_correlations_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecodingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'decoding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TickerList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'decoding',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
