# Generated by Django 4.2.7 on 2023-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_correlationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationsFull',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_A', models.CharField(max_length=20)),
                ('name_A', models.CharField(max_length=100)),
                ('sector_A', models.CharField(max_length=50)),
                ('ticker_B', models.CharField(max_length=20)),
                ('name_B', models.CharField(max_length=100)),
                ('sector_B', models.CharField(max_length=50)),
                ('correlation', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'correlations_full',
                'ordering': ('correlation',),
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CorrelationDetails',
        ),
    ]
