# Generated by Django 4.2.7 on 2023-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_correlationsfull_delete_correlationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationsFullDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'correlations_full',
                'managed': False,
            },
        ),
    ]
