# Generated by Django 4.2.7 on 2023-12-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_correlationsfulldb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correlationsfull',
            options={'managed': False, 'ordering': ['-correlation']},
        ),
    ]
