# Generated by Django 4.2.7 on 2023-12-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_correlation_correlationfull_ticker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correlation',
            options={'managed': False, 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='correlationfull',
            options={'managed': False, 'ordering': ('id',)},
        ),
    ]
