# Generated by Django 5.0 on 2023-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_correlation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('candles_id', models.AutoField(primary_key=True, serialize=False)),
                ('secid', models.CharField(max_length=20)),
                ('pr_open', models.DateTimeField()),
                ('pr_close', models.DateTimeField()),
                ('pr_high', models.FloatField()),
                ('pr_low', models.FloatField()),
                ('val', models.FloatField()),
                ('vol', models.FloatField()),
                ('begin_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'candles',
                'ordering': ('candles_id',),
                'managed': False,
            },
        ),
    ]
